# Report Server Connection Config

# conntype : jdbc, jndi
# jdbc type : SQL_Server,  MySQL, Oracle, Tibero, DB2, Sybase, UserCustom

# version SQL_Server 2000, 2005, 2008, 2012
dataconnection.reuse.maxcount=20
dataconnection.count=3

dataconnection1.conntype=jdbc
dataconnection1.type=Oracle
dataconnection1.dbname=oracle1
dataconnection1.version=
#dataconnection1.url=jdbc:oracle:thin:@202.31.182.130:1521:NECTE
#dataconnection1.url=jdbc:oracle:thin:@202.31.182.130:1521:necte
dataconnection1.url=jdbc:oracle:thin:@127.0.0.1:1521:orcl
#dataconnection1.user=eva4rd
dataconnection1.user=EVA4RD
#dataconnection1.password=eva4rd
dataconnection1.password=didtjdvudrk512
dataconnection1.encoding=
dataconnection1.decoding=

dataconnection2.conntype=jdbc
dataconnection2.type=UserCustom
dataconnection2.dbname=usercustom1
dataconnection2.version=
dataconnection2.driver=cubrid.jdbc.driver.CUBRIDDriver
dataconnection2.url=
dataconnection2.user=
dataconnection2.password=
dataconnection2.encoding=
dataconnection2.decoding=

dataconnection3.conntype=jndi
dataconnection3.dbname=dbname
dataconnection3.jndiname=jndiname
dataconnection3.encoding=
dataconnection3.decoding=