
db.initsize=3
db.maxactive=5
db.maxidle=5


#\uac1c\ubc1c\uc11c\ubc84

db.driver=com.tmax.tibero.jdbc.TbDriver
#db.url=jdbc:tibero:thin:@192.168.0.100:8629:tibero
db.url=jdbc:tibero:thin:@192.168.0.133:8629:tibero

#db.username=EVA6TH
#db.password=ENC(nKUtA9U4huVkgag3VVKkhyKl28mQuKv+)
db.username=EVA6TH
db.password=ENC(SOOy3dOaFX1rSbo9eJwOFg==)


#fileupload.path=/KEDI/upload
fileupload.path=/files

#\uac1c\ubc1c\uc6d0 E-Mail \uc124\uc815
#mail.smtp.auth=true
#mail.smtp.starttls.enable=false
#mail.smtp.port=25
#mail.host=210.107.250.124
#mail.id=teva
#mail.password=kedi2018**


#\ud6c4\uc774\uc988 E-Mail \uc124\uc815
mail.smtp.auth=true
mail.smtp.starttls.enable=false
mail.smtp.port=587
mail.host=mail.w.necte.or.kr
mail.id=no-reply@necte.or.kr
mail.password=whoami14!!
mail.vendor=whois
mail.fromemail=no-reply@necte.or.kr
