--E5_POOL_M 데이터중 TEL_HP 없거나 ,NAME,TEL_HP 키로 중복인데이터 제외하고 복제
INSERT INTO EVA6TH.EVA_POOL_M (
    CI, DI, ROLE, USR_ID, PRIV_YN, PRIV_DTTM, QUAN_YN, QUAL_YN, DISQ_YN_1, DISQ_UNIV_CD_1, 
    DISQ_YN_2, DISQ_UNIV_CD_2, NAME, GENDER, TEL_HP, TEL_HOME, BIRTHDAY, ADDR_HOME_ZIPCODE, 
    ADDR_HOME, ADDR_HOME_DETAIL, UNIV_CD, JOB_NM, POSITION, DEPT, EMAIL, ADDR_JOB_ZIPCODE, 
    ADDR_JOB, ADDR_JOB_DETAIL, TEL_JOB, RESUME_1, RESUME_2, EDU_DIV, JOB_CD, UNIV_DIV, 
    CTPV_CD, DEL_YN, INPT_ID, INPT_DT, LAST_CHNRG_ID, LAST_CHG_DT
)
SELECT
    NULL AS CI,
    NULL AS DI,
    'U' AS ROLE,
    sub.USR_ID,
    sub.PRIV_YN,
    sub.PRIV_DTTM,
    sub.QUAN_YN,
    sub.QUAL_YN,
    NULL AS DISQ_YN_1,
    sub.DISQ_UNIV_CD_1,
    NULL AS DISQ_YN_2,
    sub.DISQ_UNIV_CD_2,
    sub.NAME,
    sub.GENDER,
    sub.TEL_HP,
    sub.TEL_HOME,
    sub.BIRTHDAY,
    sub.ADDR_HOME_ZIPCODE,
    sub.ADDR_HOME,
    sub.ADDR_HOME_DETAIL,
    NULL AS UNIV_CD,
    sub.JOB_NM,
    sub.POSITION,
    sub.DEPT,
    sub.EMAIL,
    sub.ADDR_JOB_ZIPCODE,
    sub.ADDR_JOB,
    sub.ADDR_JOB_DETAIL,
    sub.TEL_JOB,
    sub.RESUME_1,
    sub.RESUME_2,
    sub.EDU_DIV,
    sub.JOB_CD,
    sub.UNIV_DIV,
    NULL AS CTPV_CD,
    'N' AS DEL_YN,
    NULL AS INPT_ID,  -- 필요에 따라 수정
    SYSDATE AS INPT_DT,  -- 현재 시간으로 설정
    NULL AS LAST_CHNRG_ID,  -- 필요에 따라 수정
    SYSDATE AS LAST_CHG_DT  -- 현재 시간으로 설정
FROM (
    SELECT 
        a.*,
        ROW_NUMBER() OVER (PARTITION BY USR_ID ORDER BY FRST_REGST_DTTM DESC) AS rn_usr,
        ROW_NUMBER() OVER (PARTITION BY TEL_HP ORDER BY FRST_REGST_DTTM DESC) AS rn_tel
    FROM 
        EVA5TH.E5_POOL_M a
    WHERE 
        a.USR_ID IS NOT NULL AND a.TEL_HP IS NOT NULL AND NAME IS NOT NULL
) sub
WHERE sub.rn_usr = 1 AND sub.rn_tel = 1;

--E5_POOL_DEGREE 데이터 EVA_POOL_DEGREE에 복사 학력
INSERT INTO EVA_POOL_DEGREE (
	DI,
    USR_ID,
    SEQ,
    EDU_YM,
    UNIV_CD,
    UNIV_NM,
    LOC_CD,
    LOC_CD_NM,
    DEG_CD,
    DEG_CD_NM,
    MAJOR,
    DEL_YN   
)
SELECT
	NULL AS DI,
    USR_ID,
    SEQ,
    EDU_YM,
    NULL AS UNIV_CD,
    UNIV_NM,
    LOC_CD,
    LOC_CD_NM,
    DEG_CD,
    DEG_CD_NM,
    MAJOR,
    DEL_YN  
FROM EVA5TH.E5_POOL_DEGREE_H;

--E5_POOL_FULLTIME_TEACHER_H 데이터 EVA_POOL_FULLTIME_TEACHER 복사 재직경력
INSERT INTO EVA_POOL_FULLTIME_TEACHER (
	DI,
	USR_ID,
	SEQ,
	JOB_ST_YM,
	JOB_ED_YM,
	UNIV_CD,
	UNIV_NM,
	DEPT,
	DEL_YN	
)
SELECT
	 NULL AS DI,
	 USR_ID,
	 SEQ,
	 JOB_ST_YM,
	 JOB_ED_YM,
	 UNIV_CD,
	 UNIV_NM,
	 DEPT,
	 DEL_YN
FROM EVA5TH.E5_POOL_FULLTIME_TEACHER_H; 

--E5_POOL_EVA_EXP_H 데이터 EVA_POOL_EVA_EXP 복사 위원경험
INSERT INTO EVA_POOL_EVA_EXP(
	DI,
	USR_ID,
	SEQ,
	TYPE_DIV,
	PART_YEAR,
	EVA_NM,
	ORG,
	ROLE_CD,
	ROLE_CD_NM,
	DEL_YN
)
SELECT
	NULL AS DI,
	USR_ID,
	SEQ,
	TYPE_DIV,
	PART_YEAR,
	EVA_NM,
	ORG,
	ROLE_CD,
	ROLE_CD_NM,
	DEL_YN
FROM EVA5TH.E5_POOL_EVA_EXP_H;
