drop table EVA6TH.EVA_POOL_SCHE;
drop table EVA6TH.EVA_POOL_M;
drop table EVA6TH.EVA_POOL_DEGREE;
drop table EVA6TH.EVA_POOL_FULLTIME_TEACHER;
drop table EVA6TH.EVA_POOL_EVA_EXP;
drop table EVA6TH.EVA_POOL_DISQ_UNIV;
drop table EVA6TH.EVA_POOL_APPL;


--EVA_POOL_SCHE 진단위원 후보자 활동계획  
CREATE TABLE EVA6TH.EVA_POOL_SCHE (
	"PERIOD_DIV_CD"	VARCHAR2(3),
	"EVA_YEAR"       VARCHAR2(4),
	"POOL_CD"        VARCHAR2(5),
	"POOL_CD_NM"     VARCHAR2(100),
	"ST_DT"          VARCHAR2(12),
	"ED_DT"         VARCHAR2(12),
	"STATUS_CD"      VARCHAR2(1),
	"INPT_ID"       VARCHAR2(50),
	"INPT_DT"        DATE,
	"LAST_CHNRG_ID"  VARCHAR2(50),
	"LAST_CHG_DT"    DATE,
	CONSTRAINT EVA_POOL_SCHE_PK PRIMARY KEY ("PERIOD_DIV_CD","EVA_YEAR","POOL_CD") 
);

   
   COMMENT ON TABLE EVA6TH.EVA_POOL_SCHE IS '진단위원 후보자 활동계획'; 
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."PERIOD_DIV_CD" IS '주기구분';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."EVA_YEAR" IS '진단년도';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."POOL_CD" IS '활동계획코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."POOL_CD_NM" IS '활동계획명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."ST_DT" IS '시작일';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."ED_DT" IS '종료일';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."STATUS_CD" IS '상태구분';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."INPT_ID" IS '등록자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."INPT_DT" IS '등록일시';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."LAST_CHNRG_ID" IS '최종변경자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_SCHE"."LAST_CHG_DT" IS '최종변경일시';
 

--EVA_POOL_M 진단위원 후보자 정보
CREATE TABLE EVA6TH.EVA_POOL_M (
	"CI"			VARCHAR2(88),	
	"DI"	  		VARCHAR2(64),	
	"ROLE"		    VARCHAR2(1)	NOT NULL ENABLE,
	"USR_ID"		VARCHAR2(30),
	"PRIV_YN"		VARCHAR2(1)		NOT NULL ENABLE,
	"PRIV_DTTM"		DATE			NOT NULL ENABLE,
	"QUAN_YN"		VARCHAR2(1)	,
	"QUAL_YN"		VARCHAR2(1)	,
	"DISQ_YN_1"		VARCHAR2(1)	,
	"DISQ_UNIV_CD_1" VARCHAR2(8),	
	"DISQ_YN_2"		VARCHAR2(1)	,
	"DISQ_UNIV_CD_2" VARCHAR2(8),	
	"NAME"			VARCHAR2(500),	
	"GENDER"		VARCHAR2(500),	
	"TEL_HP"		VARCHAR2(500) NOT NULL ENABLE,	
	"TEL_HOME"		VARCHAR2(500),	
	"BIRTHDAY"		VARCHAR2(500),	
	"ADDR_HOME_ZIPCODE"	VARCHAR2(500),	
	"ADDR_HOME"		VARCHAR2(500),
	"ADDR_HOME_DETAIL"	VARCHAR2(500),
	"UNIV_CD"		VARCHAR2(10),
	"JOB_NM"		VARCHAR2(500),
	"POSITION"		VARCHAR2(500),	
	"DEPT"			VARCHAR2(500),	
	"EMAIL"			VARCHAR2(500),	
	"ADDR_JOB_ZIPCODE"	VARCHAR2(500),	
	"ADDR_JOB"	VARCHAR2(500),	
	"ADDR_JOB_DETAIL"	VARCHAR2(500),	
	"TEL_JOB"	VARCHAR2(500),	
	"RESUME_1"	VARCHAR2(4000),	
	"RESUME_2"	VARCHAR2(4000),
	"EDU_DIV"	VARCHAR2(1)	,
	"JOB_CD"	VARCHAR2(1)	,
	"UNIV_DIV"	VARCHAR2(2)	,	
	"CTPV_CD"	VARCHAR2(2)	,	
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N' ,
	"IP"		VARCHAR2(50),
	"INPT_ID"	VARCHAR2(50)	,
	"INPT_DT"	DATE ,
	"LAST_CHNRG_ID"	VARCHAR2(50) ,
	"LAST_CHG_DT"	DATE ,
	CONSTRAINT EVA_POOL_M_PK PRIMARY KEY ("TEL_HP","NAME") 
);


   ALTER TABLE EVA_POOL_M ADD CONSTRAINT EVA_POOL_M_UK1 UNIQUE (DI);
   ALTER TABLE EVA_POOL_M ADD CONSTRAINT EVA_POOL_M_UK2 UNIQUE (USR_ID);
   
   COMMENT ON TABLE EVA6TH.EVA_POOL_M IS '진단위원 후보자 정보';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."CI" IS 'CI';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DI" IS 'DI';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ROLE" IS '권한';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."USR_ID" IS '사용자ID(EMAIL)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."PRIV_YN" IS '개인정보수집동의여부';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."PRIV_DTTM" IS '개인정보수집동의일자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."QUAN_YN" IS '정량지원여부';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."QUAL_YN" IS '정성지원여부';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DISQ_YN_1" IS '결격사항체크여부(기피제척)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DISQ_UNIV_CD_1" IS '기피제척대학코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DISQ_YN_2" IS '결격사항체크여부(수행곤란대학)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DISQ_UNIV_CD_2" IS '수행곤란대학코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."NAME" IS '성명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."GENDER" IS '성별';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."TEL_HP" IS '연략처(집)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."TEL_HOME" IS '연략처(자택)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."BIRTHDAY" IS '생년월일';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ADDR_HOME_ZIPCODE" IS '자택_우편번호';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ADDR_HOME" IS '자택_주소';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ADDR_HOME_DETAIL" IS '자택_상세주소';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."UNIV_CD" IS '대학코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."JOB_NM" IS '직장명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."POSITION" IS '직위';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DEPT" IS '소속학과';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."EMAIL" IS 'email';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ADDR_JOB_ZIPCODE" IS '직장_우편주소';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ADDR_JOB" IS '직장주소';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."ADDR_JOB_DETAIL" IS '직장_상세주소';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."TEL_JOB" IS '직장연락처';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."RESUME_1" IS '자기소개1';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."RESUME_2" IS '자기소개2';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."EDU_DIV" IS 'EDU_DIV:사범대설치,미설치 등';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."JOB_CD" IS '공모분야 1: 교수, 2:교직원';   
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."UNIV_DIV" IS '근무대학구분 코드 EDNST_ADDR_M 테이블참조 학교유형코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."CTPV_CD" IS '근무대학 소재지 코드  EDNST_ADDR_M 테이블참조 시도코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."IP" IS '등록된IP';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."INPT_ID" IS '등록자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."INPT_DT" IS '등록일시';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."LAST_CHNRG_ID" IS '최종변경자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_M"."LAST_CHG_DT" IS '최종변경일시';
   
--EVA_POOL_DEGREE 진단위원 후보자 학력   
CREATE TABLE EVA6TH.EVA_POOL_DEGREE (
	"DI"	  VARCHAR2(64),	
	"USR_ID"  VARCHAR2(50)	NOT NULL ENABLE,
	"SEQ"	  NUMBER  NOT NULL ENABLE,
	"EDU_YM"  VARCHAR2(6),
	"UNIV_CD" VARCHAR2(10),
	"UNIV_NM" VARCHAR2(100),
	"LOC_CD"	VARCHAR2(100),
	"LOC_CD_NM" VARCHAR2(100),
	"DEG_CD"	VARCHAR2(100),
	"DEG_CD_NM"	VARCHAR2(100),
	"MAJOR"		VARCHAR2(100),	
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N' ,
	"INPT_ID"	VARCHAR2(50),
	"INPT_DT"	DATE,
	"LAST_CHNRG_ID"	VARCHAR2(50),
	"LAST_CHG_DT"	DATE,
	CONSTRAINT EVA_POOL_DEGREE_PK PRIMARY KEY ("USR_ID","SEQ") 
);
	
	 ALTER TABLE EVA_POOL_DEGREE ADD CONSTRAINT EVA_POOL_DEGREE_UK1 UNIQUE (DI, USR_ID,SEQ);
   
   COMMENT ON TABLE EVA6TH.EVA_POOL_DEGREE IS '진단위원 후보자 학력'; 
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."USR_ID" IS '사용자ID(EMAIL)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."SEQ" IS '순번';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."EDU_YM" IS '학력취득년월';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."UNIV_CD" IS '대학코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."UNIV_NM" IS '대학명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."LOC_CD" IS '소재지코드(지역코드-권역)';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."LOC_CD_NM" IS '소재지코드명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."DEG_CD" IS '학위코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."DEG_CD_NM" IS '학위코드명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."MAJOR" IS '세부전공';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."INPT_ID" IS '등록자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DEGREE"."INPT_DT" IS '등록일시';

   
--EVA_POOL_FULLTIME_TEACHER 진단위원 후보자 활동계획  
CREATE TABLE EVA6TH.EVA_POOL_FULLTIME_TEACHER (	
	"DI"	  VARCHAR2(64),	
	"USR_ID"		VARCHAR2(50) NOT NULL ENABLE ,
	"SEQ"           NUMBER NOT NULL ENABLE ,
	"JOB_ST_YM"     VARCHAR2(6),
	"JOB_ED_YM"     VARCHAR2(6),
	"UNIV_CD"       VARCHAR2(8),
	"UNIV_NM"       VARCHAR2(100),
	"DEPT"          VARCHAR2(50),
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N' ,
	"INPT_ID"      VARCHAR2(50),
	"INPT_DT"       DATE,
	
	
	CONSTRAINT EVA_POOL_FULLTIME_TEACHER_PK PRIMARY KEY ("USR_ID","SEQ") 
);

   ALTER TABLE EVA_POOL_FULLTIME_TEACHER ADD CONSTRAINT EVA_POOL_FULLTIME_TEACHER_UK1 UNIQUE (DI, USR_ID,SEQ);
    
   COMMENT ON TABLE EVA6TH.EVA_POOL_FULLTIME_TEACHER IS '진단위원 후보자 학력'; 
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."USR_ID" IS '사용자ID';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."SEQ" IS '순번';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."JOB_ST_YM" IS '근무시작년월'; 
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."JOB_ED_YM" IS '근무종료년월';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."UNIV_CD" IS '대학코드';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."UNIV_NM" IS '대학명';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."DEPT" IS '소속학과';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."DEL_YN" IS '삭제여부';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."INPT_ID" IS '등록자';
   COMMENT ON COLUMN "EVA6TH"."EVA_POOL_FULLTIME_TEACHER"."INPT_DT" IS '등록일시';


--EVA_POOL_EVA_EXP 진단위원 후보자 진단활동경험   
CREATE TABLE EVA6TH.EVA_POOL_EVA_EXP (	
	"DI"	  VARCHAR2(64),		
	"USR_ID"	VARCHAR2(50) NOT NULL ENABLE,
	"SEQ"		NUMBER NOT NULL ENABLE,
	"TYPE_DIV"	VARCHAR2(1) NOT NULL ENABLE,
	"PART_YEAR"	VARCHAR2(4),
	"EVA_NM"	VARCHAR2(100),
	"ORG"		VARCHAR2(100),
	"ROLE_CD"	VARCHAR2(50),
	"ROLE_CD_NM" VARCHAR2(100),
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N' ,
	"INPT_ID"	 VARCHAR2(50),
	"INPT_DT"	 DATE	,
	
	
	CONSTRAINT EVA_POOL_EVA_EXP_PK PRIMARY KEY ("USR_ID","SEQ","TYPE_DIV") 
);	

	ALTER TABLE EVA_POOL_EVA_EXP ADD CONSTRAINT EVA_POOL_EVA_EXP_UK1 UNIQUE (DI, USR_ID,SEQ,TYPE_DIV);
	 
	COMMENT ON TABLE EVA6TH.EVA_POOL_EVA_EXP IS '진단위원 후보자 진단활동경험 ';  
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."USR_ID" IS '사용자ID';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."SEQ" IS '순번';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."TYPE_DIV" IS '진단/준비구분 (1: 진단, 2: 준비)';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."PART_YEAR" IS '참여연도';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."EVA_NM" IS '평가명칭';
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."ORG" IS '주관기관';
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."ROLE_CD" IS '역할코드';
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."ROLE_CD_NM" IS '역할코드명';
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."DEL_YN" IS '삭제여부';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."INPT_ID" IS '등록자';
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_EVA_EXP"."INPT_DT" IS '등록일시';



--EVA_POOL_DISQ_UNIV 기피제척대학
CREATE TABLE EVA6TH.EVA_POOL_DISQ_UNIV (			
	"DI"	  VARCHAR2(64),
	"PERIOD_DIV_CD" VARCHAR2(3) NOT NULL ENABLE,
	"EVA_YEAR" 		VARCHAR2(4) NOT NULL ENABLE,
	"POOL_CD"		VARCHAR2(5) NOT NULL ENABLE,
	"USR_ID"		VARCHAR2(50) NOT NULL ENABLE,
	"DISQ_DIV"		VARCHAR2(2) NOT NULL ENABLE,
	"SEQ"			NUMBER NOT NULL ENABLE ,
	"DISQ_UNIV_CD"	VARCHAR2(8),
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N' ,
	"INPT_ID"	 	VARCHAR2(50),
	"INPT_DT"	 	DATE	,
	
	
	CONSTRAINT EVA_POOL_DISQ_UNIV_PK PRIMARY KEY ("PERIOD_DIV_CD","EVA_YEAR","POOL_CD","USR_ID","DISQ_DIV","SEQ") 
);	

	ALTER TABLE EVA_POOL_DISQ_UNIV ADD CONSTRAINT EVA_POOL_DISQ_UNIV_UK1 UNIQUE (DI,PERIOD_DIV_CD,EVA_YEAR,POOL_CD,USR_ID,DISQ_DIV,SEQ);
	
  COMMENT ON TABLE EVA6TH.EVA_POOL_DISQ_UNIV IS '기피제척대학';  
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."PERIOD_DIV_CD" IS '주기구분';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."EVA_YEAR" IS '진단년도';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."POOL_CD" IS '활동계획코드';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."USR_ID" IS '사용자ID';	
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."DISQ_DIV" IS '기피제척구분 1:직계가족or배우자 2:기타수행곤란대학';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."SEQ" IS '순번';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."DISQ_UNIV_CD" IS '기피제척대학코드';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."DEL_YN" IS '삭제여부';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."INPT_ID" IS '등록자';
  COMMENT ON COLUMN "EVA6TH"."EVA_POOL_DISQ_UNIV"."INPT_DT" IS '등록일시';

--EVA_POOL_APPL 진단 활동 신청 내역
CREATE TABLE EVA6TH.EVA_POOL_APPL (	
	"DI"	  VARCHAR2(64),	
	"PERIOD_DIV_CD" VARCHAR2(3) NOT NULL ENABLE,
	"EVA_YEAR" 		VARCHAR2(4) NOT NULL ENABLE,
	"POOL_CD"		VARCHAR2(5) NOT NULL ENABLE,
	"POOL_CD_NM"	VARCHAR2(100) ,
	"USR_ID"		VARCHAR2(50) NOT NULL ENABLE,
	"NAME"			VARCHAR2(50) ,
	"APPL_YN"		VARCHAR2(1),
	"APPL_YN_DT"	DATE,
	"DISQ_YN_1"		VARCHAR2(1) DEFAULT 'N'	,	
	"DISQ_YN_2"		VARCHAR2(1)	DEFAULT 'N',		
	"SEL_RSLT"		VARCHAR2(1) DEFAULT 'N',
	"SEC_PLEDGE_YN"	VARCHAR2(1),
	"SEC_PLEDGE_YN_DT"	DATE	,
	"SIGN_1"   CLOB,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N' ,
	"INPT_ID"	 	VARCHAR2(50),
	"INPT_DT"	 	DATE	,
	"LAST_CHNRG_ID" VARCHAR2(50),
	"LAST_CHG_DT"	DATE	,
	
	CONSTRAINT EVA_POOL_APPL_PK PRIMARY KEY ("PERIOD_DIV_CD", "EVA_YEAR", "POOL_CD", "USR_ID") 
);	

	ALTER TABLE EVA_POOL_APPL ADD CONSTRAINT EVA_POOL_APPL_UK1 UNIQUE (DI,PERIOD_DIV_CD,EVA_YEAR,POOL_CD,USR_ID);
	
	COMMENT ON TABLE EVA6TH.EVA_POOL_APPL IS '진단위원 후보자 진단활동신청내역 ';  
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."PERIOD_DIV_CD" IS '주기구분';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."EVA_YEAR" IS '진단년도';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."POOL_CD" IS '활동계획코드';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."POOL_CD_NM" IS '활동계획명';	
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."USR_ID" IS '사용자ID';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."NAME" IS '성명';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."APPL_YN" IS '제출여부 Y:제출완료,N:미제출';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."APPL_YN_DT" IS '제출일자';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."DISQ_YN_1" IS '결격사항체크여부(기피제척)';    
    COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."DISQ_YN_2" IS '결격사항체크여부(수행곤란대학)';  
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."SEL_RSLT" IS '선정결과 Y:선정,N:미선정';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."SEC_PLEDGE_YN" IS '보안서약서 동의여부 Y:동의,N:미동의';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."SEC_PLEDGE_YN_DT" IS '보안서약서 동의일자';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."SIGN_1" IS '보안서약서 사인';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."DEL_YN" IS '삭제여부';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."INPT_ID" IS '등록자';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."INPT_DT" IS '등록일시';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."LAST_CHNRG_ID" IS '최종변경자';
	COMMENT ON COLUMN "EVA6TH"."EVA_POOL_APPL"."LAST_CHG_DT" IS '최종변경일시';
	

--EVA_POOL_M 진단위원 후보자 삭제 정보
CREATE TABLE EVA6TH.EVA_POOL_M_DEL(
	"NAME"			VARCHAR2(500),	
	"USR_ID"		VARCHAR2(30),
	"DEL_DT"	DATE
);
	


/***********************************************************************************
 						2025.01.24 - 실서버 적용
***********************************************************************************/

--EVA_POOL_M_DEL 컬럼 추가
ALTER TABLE EVA_POOL_M_DEL 
ADD (
    DEL_SEQ NUMBER PRIMARY KEY,
    RMRK VARCHAR2(2000 BYTE)
);

--EVA_POOL_M_DEL 시퀸스 추가
CREATE SEQUENCE EVA_POOL_M_DEL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--EVA_POOL_M 컬럼 추가
ALTER TABLE EVA_POOL_M ADD FILE_ID CHAR(14);


/***********************************************************************************
 						2025.02.28 - 실서버 적용
***********************************************************************************/

